theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag

# Add baseurl if using project site
baseurl: /Astro-Recognizer  # Your repository name
url: https://shaek666.github.io

title: Astro Recognizer
description: An image classification API that classifies 17 different types of astronomical elements found.

author:
  name: Shaek