remote_theme: abhinavs/moonwalk
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag  

title: Astro Recognizer
description: An image classification API that classifies 17 different types of astronomical elements found.

author:
  name: Shaek